### ISSUE TITLE
Crashing with new update

### ISSUE THREAD

**Issue by senahf** [dlehn/Skype-Utility-Project#12]
When I upgraded Skype and put in the dll, it crashes on startup.

Any fixes?

**Comment by dlehn** [comment]
Well, obviously that's not supposed to happen. 
Which version of Skype are you using now? Did it work for you with an older Skype version?  

I just tried updating and cannot find any issues running SUP 1.3.4 with Skype 7.1.0.105.

General suggestions for fixing problems with SUP are:
- Try to (re-)install the [MSVC++ 2013 redistributables](https://www.microsoft.com/en-us/download/details.aspx?id=40784) (the x86 version).
- (Re-)Install the [DirectX 9 runtime](http://www.microsoft.com/en-us/download/details.aspx?id=8109) (don't select any of the additional crap they're trying to get you to download).
- Delete SUP's configuration file (`sup.ini` located in `C:\Users\*Your Name\AppData\Roaming\Skype\`)

**Comment by senahf** [comment]
Oh, I got it working, I guess it was just a problem with the Skype update for me. Thanks!

**Comment by dlehn** [comment]
Wonderful, thanks for using SUP :smile:
