### ISSUE TITLE
Banner doesn't hide when working in "Separated Windows" mode

### ISSUE THREAD

**Issue by malaguer** [dlehn/Skype-Utility-Project#14]
First of all, thank you so much for the plugin. It's being very useful.

Could you modify it to also include the "Separated Window" mode (I'm spanish, not sure how that menu option is written in english, sorry) and make the banner disappear in this mode too?

Thank you in advance.

**Comment by dlehn** [comment]
Which version of Skype are you using?  
I think you're referring to the "Split Window View" option (where the contact list and conversations are displayed in separate windows). As far as I can tell, the banners should be hidden in this mode, too.  
http://imgur.com/sZ0kzdD

**Comment by malaguer** [comment]
Yes! That's exactly the Window View Mode I refer to.

My Skype version is: 7.1.60.105. It should update automatically itself.

But I'm glad to see that I can get rid of the whole banners. Do you believe the version can be the problem?

**Comment by malaguer** [comment]
BTW I tried to update manually and it says I have the last version available...

Here's my data:

Windows 8.1 x64
Skype 7.1.60.105 (Spanish version)

**Comment by dlehn** [comment]
I hate Skype and its arbitrary update policy. New versions are always rolled out randomly only to a part of the users, it can sometimes take weeks until everyone gets a new Skype version via auto update.  
I'm still on version 7.1.0.105, so since you're using a newer version I'm guessing that will be the cause of the problem. I'll download this new version and see if I can find out what they messed up this time...

**Comment by malaguer** [comment]
Ok, thanks for trying. And please keep the development while you can. Skype seems to start becoming like MSN all full of banners and Ads.

Good job anyway, I'll stay tunned to your project. :)

**Comment by dlehn** [comment]
Thanks for the encouragement, I'll do what I can :)  
At the very least I can reproduce the problem, so this shouldn't be too hard to fix. A small workaround for the moment is to simply resize the conversation window horizontally, that will cause the layout to update and the banner will be hidden as it is supposed to.

**Comment by malaguer** [comment]
Man, you're fast thinking. :) If you've seen the new changes in just a few minutes, I'm sure you'll get it shortly (I hope so!).

I'm glad you found the last spanish version (I don't know if the language is important).

Well, I'll let you work at your own pace. If you need me to test something just tell me, I'll be glad to help. :)

**Comment by dlehn** [comment]
It's not a problem exclusive to the Spanish version, the order in which the controls are initialized seems to have changed in the most recent versions, which breaks my code (after manually updating I'm now on 7.2.0.103 where we have the same problem).  

SUP version [1.3.6](https://github.com/dlehn/Skype-Utility-Project/releases/tag/1.3.6) is now available and should (as far as I can tell) fix this issue. Let me know if you're still experiencing any issues.

**Comment by malaguer** [comment]
I've tried your new release and it seems to work everything fine. Thank you so much for your work! :)
