### ISSUE TITLE
Skype 7.2.0.103 dont load SUP d3d9.dll

### ISSUE THREAD

**Issue by ThecaTTony** [dlehn/Skype-Utility-Project#15]
The updated version of Skype dont load anymore the d3d9.dll file from \Skype\Phone.
There is no menu, or adblock working.

Thanks and regards.

**Comment by dlehn** [comment]
Are you already using SUP version [1.3.6](https://github.com/dlehn/Skype-Utility-Project/releases/tag/1.3.6)?  
There were a few issues with the newest Skype version which should have been fixed in this update.

**Comment by ThecaTTony** [comment]
Sorry, i installed SUP by Chocolatey and that version is outdated (1.3.4). Today i will test the latest version, thanks for the reply.

**Comment by dlehn** [comment]
Well, technically 1.3.6 (and also 1.3.5) are already [available via Chocolatey](https://chocolatey.org/packages/skype-utility-project/1.3.6), but unfortunately the moderators there take ages to approve new packages, and you won't get the new versions automatically until they are approved.  
You can still install the newer versions via Chocolatey by manually specifying the version number, in this case:
`choco install skype-utility-project -version 1.3.6`

**Comment by ThecaTTony** [comment]
Yep, latest version works OK. Sorry for the useless report. Regards.

**Comment by dlehn** [comment]
Not a problem. Closed.
