### ISSUE TITLE
Visual C++ Redist 2013 is required

### ISSUE THREAD

**Issue by szepeviktor** [dlehn/Skype-Utility-Project#21]
Please add it to the readme.
http://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by szepeviktor** [comment]
DirectX DLL is a clever point of code injection.

**Comment by dlehn** [comment]
Added a "Troubleshooting" section to the readme, along with some other potential problems I could think of. Hope that will do.

**Comment by szepeviktor** [comment]
Thank you.
