### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by unmog** [dlehn/Skype-Utility-Project#23]
I love the utility here but Im unable to use it any longer. I guess my skype updated or something. I got an error just today that says "This app cant run on your PC. To find a version for your PC, check with the software publisher" So I reinstalled Skype. It worked. I redownloaded the file from here and replaced the dll's, then it gave me the same error again... :(

**Comment by nestdimon** [comment]
What version of Skype and SUP do you have? 

The latest Skype 7.14.0.106 with SUP 1.4.1 works fine.

**Comment by unmog** [comment]
Mine says 7.15.0.102

Nevermind though. I think I figured out the problem. I guess when skype updated it didnt get rid of the old one completely and it was trying to launch skype from whatever the older now emptied skype location was. Unsure what caused it but when I uninstalled it and deleted all the shortcuts and stuff, the reinstalled it again it was working fine. I can confirm SUP works with 7.15 now as well. :)
