### ISSUE TITLE
Ads are displayed

### ISSUE THREAD

**Issue by szepeviktor** [dlehn/Skype-Utility-Project#24]
- SUP v1.4.0
- Windows 10 Pro 64 bit Hungarian
- Skype 7.14.0.106 from msi package

![skype-nohide](https://cloud.githubusercontent.com/assets/952007/11880918/dbac2e0a-a503-11e5-9363-449639dc7325.jpg)

Could you help me?

**Comment by szepeviktor** [comment]
Even with 7.17 from http://www.skype.com/go/getskype-full.

**Comment by szepeviktor** [comment]
> Does not apply to ads displayed on the "Home" page.

I am sorry!
Does it apply to ads in a conversation/conference?

**Comment by dlehn** [comment]
Hi Viktor, yes the "Hide Ads" feature works for the ad banners in conversation windows only (that at least works quite well :wink:).  
I tried hiding the ads on the home page as well, but unfortunately Skype uses a custom renderer for those, so there's not much I can do about them.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by iuliangcata** [comment]
Use Adguard Desktop :)
