### ISSUE TITLE
Ads are showing up

### ISSUE THREAD

**Issue by jonatino** [dlehn/Skype-Utility-Project#30]
First of all, thank you for this awesome project!

I've noticed in the most recent version of Skype, ads have started showing up again.

https://dl.dropboxusercontent.com/s/0cav73h28phwqg8/2017-11-07_20-58-11.png

Thanks!

**Comment by szepeviktor** [comment]
From the readme:

> Hide Ads: Hide the advertisement banners above conversations. This will not affect Ads on the Skype "Home" page.
