### ISSUE TITLE
Chocolatey Package

### ISSUE THREAD

**Issue by cpmcgrath** [dlehn/Skype-Utility-Project#9]
Hi Guys,
Thanks for this fantastic project. Any chance of releasing it as a chocolatey package to make the installation easier? https://chocolatey.org/

**Comment by dlehn** [comment]
Well... I just had a look at their documentation and to be honest this looks to me like a freaking lot of effort to avoid downloading and extracting a single file (that is **1** in numbers) to a directory. Also, updating the version information, building the package and uploading it for every new release does add quite a bit of overhead to the release process (relatively speaking, compared to zipping a file and dragging it into my browser to upload it).  

Personally, I'm not quite convinced that it's worth the effort. Is there anything here I'm missing? Would this do anything more than allowing the package to be installed from the command line?

**Comment by cpmcgrath** [comment]
There's two reasons I would like a chocolatey package.
1. It lets me add it to my clean install script - When I setup a new computer, chocolatey means I don't have to remember all the little tools I like, to get SUP without having to think about it is appealing to me.
2. I don't have to go to any trouble to get updates, I can just run "cup all" and if there's an update, I get it. Of course, I'm not sure how many more updates you're planning as it's pretty damn perfect as is.

**Comment by dlehn** [comment]
First of all, we don't plan anything here. We just add stuff when we're bored or when there's something that annoys us (or someone else).  

I can see how especially the update thing would be useful. You wouldn't happen to be familiar with setting up such a package?  
From what I've seen in their documentation and the examples, I would have no idea how to set up the installation (in the examples they're using installers, we just want to copy one file) or how to tell it to install into the Skype directory by default (which is different for 32 and 64 bit versions of Windows, or may be in a custom location altogether). And no, I don't want to create a custom installer, that would definitely be overkill. :wink:

**Comment by cpmcgrath** [comment]
I don't currently have experience, but I am planning on making a package for my own project soon.

I'd be happy to create the chocolatey package, but as you identified, it will still be an extra step to do a release, I'll see if while I'm at it I can figure out a way to make it as simple as possible.

**Comment by dlehn** [comment]
Well, if you're going through the trouble of creating such a package, I'll be happy to upload it and keep it up to date.  
Once the package is set up, the effort should be... well... at least bearable. Maybe you (or I) could then write a script to automate it altogether, after all it should only require changing the version number and running a few console commands.

**Comment by nestdimon** [comment]
It seems to be too complicated for common user to install such package. I'd prefer [Inno Setup](http://www.jrsoftware.org/isinfo.php). If you need I can create installer with it.

**Comment by cpmcgrath** [comment]
The main advantage of a package manager is that it's an easy way to distribute updates. A normal installer might make an installation easy, but it's not going to notify users when an update is available.

Yes you can write code in the product to notify users, but my experience is it's hard to get the user experience of it right.

Chocolatey may still be a niche product, but its popularity is growing and with tools like the Chocolatey GUI, it will become accessible to those who aren't comfortable with the command line.

**Comment by dlehn** [comment]
Chocolatey installation is now supported, thanks to @cpmcgrath, see #10.
